name: Copy images to dockerhub devnet/testnet
on:
  push:
    branches:
      - devnet
      - testnet

permissions:
  contents: read
  id-token: write #required for GCP Workload Identity federation

jobs:
  copy-images-to-docker-hub:
    with:
      image_tag_prefix: ${{ github.ref_name }}
    secrets: inherit
